# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'superSpider.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(598, 354)
        self.SDay2 = QtGui.QRadioButton(Dialog)
        self.SDay2.setGeometry(QtCore.QRect(80, 30, 131, 16))
        self.SDay2.setChecked(True)
        self.SDay2.setAutoRepeatInterval(101)
        self.SDay2.setObjectName(_fromUtf8("SDay2"))
        self.SDay1 = QtGui.QRadioButton(Dialog)
        self.SDay1.setGeometry(QtCore.QRect(80, 60, 90, 16))
        self.SDay1.setObjectName(_fromUtf8("SDay1"))
        self.resResultdate = QtGui.QDateEdit(Dialog)
        self.resResultdate.setGeometry(QtCore.QRect(180, 60, 110, 22))
        self.resResultdate.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 1, 14), QtCore.QTime(0, 0, 0)))
        self.resResultdate.setCalendarPopup(True)
        self.resResultdate.setObjectName(_fromUtf8("resResultdate"))
        self.resResultdate2 = QtGui.QDateEdit(Dialog)
        self.resResultdate2.setGeometry(QtCore.QRect(330, 60, 110, 22))
        self.resResultdate2.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 1, 28), QtCore.QTime(0, 0, 0)))
        self.resResultdate2.setCalendarPopup(True)
        self.resResultdate2.setObjectName(_fromUtf8("resResultdate2"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 56, 12))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 56, 12))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(90, 110, 56, 12))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 56, 12))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(300, 60, 21, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(300, 110, 21, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.logOfProgress = QtGui.QPlainTextEdit(Dialog)
        self.logOfProgress.setGeometry(QtCore.QRect(20, 220, 561, 101))
        self.logOfProgress.setReadOnly(True)
        self.logOfProgress.setPlainText(_fromUtf8(""))
        self.logOfProgress.setObjectName(_fromUtf8("logOfProgress"))
        self.resYongNm = QtGui.QComboBox(Dialog)
        self.resYongNm.setGeometry(QtCore.QRect(180, 160, 261, 22))
        self.resYongNm.setObjectName(_fromUtf8("resYongNm"))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resYongNm.addItem(_fromUtf8(""))
        self.resTotGamAmt1 = QtGui.QComboBox(Dialog)
        self.resTotGamAmt1.setGeometry(QtCore.QRect(180, 110, 111, 22))
        self.resTotGamAmt1.setObjectName(_fromUtf8("resTotGamAmt1"))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt1.addItem(_fromUtf8(""))
        self.resTotGamAmt2 = QtGui.QComboBox(Dialog)
        self.resTotGamAmt2.setGeometry(QtCore.QRect(330, 110, 111, 22))
        self.resTotGamAmt2.setObjectName(_fromUtf8("resTotGamAmt2"))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.resTotGamAmt2.addItem(_fromUtf8(""))
        self.startButton = QtGui.QPushButton(Dialog)
        self.startButton.setGeometry(QtCore.QRect(500, 20, 75, 23))
        self.startButton.setObjectName(_fromUtf8("startButton"))
        self.endButton = QtGui.QPushButton(Dialog)
        self.endButton.setGeometry(QtCore.QRect(500, 50, 75, 23))
        self.endButton.setObjectName(_fromUtf8("endButton"))
        self.numOfTotal = QtGui.QLabel(Dialog)
        self.numOfTotal.setGeometry(QtCore.QRect(470, 180, 101, 20))
        self.numOfTotal.setAlignment(QtCore.Qt.AlignCenter)
        self.numOfTotal.setObjectName(_fromUtf8("numOfTotal"))
        self.numOfTotalItems = QtGui.QLabel(Dialog)
        self.numOfTotalItems.setGeometry(QtCore.QRect(470, 200, 101, 20))
        self.numOfTotalItems.setAlignment(QtCore.Qt.AlignCenter)
        self.numOfTotalItems.setObjectName(_fromUtf8("numOfTotalItems"))

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.startButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.start_crawl)
        QtCore.QObject.connect(self.endButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.stop_crawl)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Crawler", None))
        self.SDay2.setText(_translate("Dialog", "오늘이후 전체물건", None))
        self.SDay1.setText(_translate("Dialog", "날짜 선택", None))
        self.label.setText(_translate("Dialog", "입찰기일", None))
        self.label_2.setText(_translate("Dialog", "금액관련", None))
        self.label_3.setText(_translate("Dialog", "감정가", None))
        self.label_4.setText(_translate("Dialog", "용도지역", None))
        self.label_5.setText(_translate("Dialog", "~", None))
        self.label_6.setText(_translate("Dialog", "~", None))
        self.resYongNm.setItemText(0, _translate("Dialog", "선택하세요", None))
        self.resYongNm.setItemText(1, _translate("Dialog", "도시지역", None))
        self.resYongNm.setItemText(2, _translate("Dialog", "주거지역", None))
        self.resYongNm.setItemText(3, _translate("Dialog", "제1종 전용주거지역", None))
        self.resYongNm.setItemText(4, _translate("Dialog", "제2종 전용주거지역", None))
        self.resYongNm.setItemText(5, _translate("Dialog", "제1종 일반주거지역", None))
        self.resYongNm.setItemText(6, _translate("Dialog", "제2종 일반주거지역", None))
        self.resYongNm.setItemText(7, _translate("Dialog", "제3종 일반주거지역", None))
        self.resYongNm.setItemText(8, _translate("Dialog", "준 주거지역", None))
        self.resYongNm.setItemText(9, _translate("Dialog", "상업지역", None))
        self.resYongNm.setItemText(10, _translate("Dialog", "중심상업지역", None))
        self.resYongNm.setItemText(11, _translate("Dialog", "일반상업지역", None))
        self.resYongNm.setItemText(12, _translate("Dialog", "근린상업지역", None))
        self.resYongNm.setItemText(13, _translate("Dialog", "유통상업지역", None))
        self.resYongNm.setItemText(14, _translate("Dialog", "공업지역", None))
        self.resYongNm.setItemText(15, _translate("Dialog", "전용공업지역", None))
        self.resYongNm.setItemText(16, _translate("Dialog", "일반공업지역", None))
        self.resYongNm.setItemText(17, _translate("Dialog", "준 공업지역", None))
        self.resYongNm.setItemText(18, _translate("Dialog", "녹지지역", None))
        self.resYongNm.setItemText(19, _translate("Dialog", "보전녹지지역", None))
        self.resYongNm.setItemText(20, _translate("Dialog", "생산녹지지역", None))
        self.resYongNm.setItemText(21, _translate("Dialog", "자연녹지지역", None))
        self.resYongNm.setItemText(22, _translate("Dialog", "관리지역", None))
        self.resYongNm.setItemText(23, _translate("Dialog", "보전관리지역", None))
        self.resYongNm.setItemText(24, _translate("Dialog", "생산관리지역", None))
        self.resYongNm.setItemText(25, _translate("Dialog", "계획관리지역", None))
        self.resYongNm.setItemText(26, _translate("Dialog", "농림지역", None))
        self.resYongNm.setItemText(27, _translate("Dialog", "자연환경보전지역", None))
        self.resTotGamAmt1.setItemText(0, _translate("Dialog", "최소", None))
        self.resTotGamAmt1.setItemText(1, _translate("Dialog", "0원", None))
        self.resTotGamAmt1.setItemText(2, _translate("Dialog", "1천만", None))
        self.resTotGamAmt1.setItemText(3, _translate("Dialog", "3천만", None))
        self.resTotGamAmt1.setItemText(4, _translate("Dialog", "5천만", None))
        self.resTotGamAmt1.setItemText(5, _translate("Dialog", "7천만", None))
        self.resTotGamAmt1.setItemText(6, _translate("Dialog", "1억", None))
        self.resTotGamAmt1.setItemText(7, _translate("Dialog", "1억5천", None))
        self.resTotGamAmt1.setItemText(8, _translate("Dialog", "2억", None))
        self.resTotGamAmt1.setItemText(9, _translate("Dialog", "2억5천", None))
        self.resTotGamAmt1.setItemText(10, _translate("Dialog", "3억", None))
        self.resTotGamAmt1.setItemText(11, _translate("Dialog", "4억", None))
        self.resTotGamAmt1.setItemText(12, _translate("Dialog", "5억", None))
        self.resTotGamAmt1.setItemText(13, _translate("Dialog", "6억", None))
        self.resTotGamAmt1.setItemText(14, _translate("Dialog", "7억", None))
        self.resTotGamAmt1.setItemText(15, _translate("Dialog", "8억", None))
        self.resTotGamAmt1.setItemText(16, _translate("Dialog", "9억", None))
        self.resTotGamAmt1.setItemText(17, _translate("Dialog", "10억", None))
        self.resTotGamAmt1.setItemText(18, _translate("Dialog", "15억", None))
        self.resTotGamAmt1.setItemText(19, _translate("Dialog", "20억", None))
        self.resTotGamAmt1.setItemText(20, _translate("Dialog", "30억", None))
        self.resTotGamAmt1.setItemText(21, _translate("Dialog", "50억", None))
        self.resTotGamAmt2.setItemText(0, _translate("Dialog", "최대", None))
        self.resTotGamAmt2.setItemText(1, _translate("Dialog", "0원", None))
        self.resTotGamAmt2.setItemText(2, _translate("Dialog", "1천만", None))
        self.resTotGamAmt2.setItemText(3, _translate("Dialog", "3천만", None))
        self.resTotGamAmt2.setItemText(4, _translate("Dialog", "5천만", None))
        self.resTotGamAmt2.setItemText(5, _translate("Dialog", "7천만", None))
        self.resTotGamAmt2.setItemText(6, _translate("Dialog", "1억", None))
        self.resTotGamAmt2.setItemText(7, _translate("Dialog", "1억5천", None))
        self.resTotGamAmt2.setItemText(8, _translate("Dialog", "2억", None))
        self.resTotGamAmt2.setItemText(9, _translate("Dialog", "2억5천", None))
        self.resTotGamAmt2.setItemText(10, _translate("Dialog", "3억", None))
        self.resTotGamAmt2.setItemText(11, _translate("Dialog", "4억", None))
        self.resTotGamAmt2.setItemText(12, _translate("Dialog", "5억", None))
        self.resTotGamAmt2.setItemText(13, _translate("Dialog", "6억", None))
        self.resTotGamAmt2.setItemText(14, _translate("Dialog", "7억", None))
        self.resTotGamAmt2.setItemText(15, _translate("Dialog", "8억", None))
        self.resTotGamAmt2.setItemText(16, _translate("Dialog", "9억", None))
        self.resTotGamAmt2.setItemText(17, _translate("Dialog", "10억", None))
        self.resTotGamAmt2.setItemText(18, _translate("Dialog", "15억", None))
        self.resTotGamAmt2.setItemText(19, _translate("Dialog", "20억", None))
        self.resTotGamAmt2.setItemText(20, _translate("Dialog", "30억", None))
        self.resTotGamAmt2.setItemText(21, _translate("Dialog", "50억 이상", None))
        self.startButton.setText(_translate("Dialog", "검색시작", None))
        self.endButton.setText(_translate("Dialog", "검색종료", None))
        self.numOfTotal.setText(_translate("Dialog", "총 페이지수", None))
        self.numOfTotalItems.setText(_translate("Dialog", "총 건수", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

